.PHONY: clean All

All:
	@echo "----------Building project:[ Homwework19Jan2021 - Debug ]----------"
	@cd "Homwework19Jan2021" && "$(MAKE)" -f  "Homwework19Jan2021.mk"
clean:
	@echo "----------Cleaning project:[ Homwework19Jan2021 - Debug ]----------"
	@cd "Homwework19Jan2021" && "$(MAKE)" -f  "Homwework19Jan2021.mk" clean
