.PHONY: clean All

All:
	@echo "----------Building project:[ Homework12Jan2021 - Debug ]----------"
	@cd "Homework12Jan2021" && "$(MAKE)" -f  "Homework12Jan2021.mk"
clean:
	@echo "----------Cleaning project:[ Homework12Jan2021 - Debug ]----------"
	@cd "Homework12Jan2021" && "$(MAKE)" -f  "Homework12Jan2021.mk" clean
