.PHONY: clean All

All:
	@echo "----------Building project:[ Homework17Nov2020 - Debug ]----------"
	@cd "Homework17Nov2020" && "$(MAKE)" -f  "Homework17Nov2020.mk"
clean:
	@echo "----------Cleaning project:[ Homework17Nov2020 - Debug ]----------"
	@cd "Homework17Nov2020" && "$(MAKE)" -f  "Homework17Nov2020.mk" clean
