.PHONY: clean All

All:
	@echo "----------Building project:[ Section7YChallange - Debug ]----------"
	@cd "Section7YChallange" && "$(MAKE)" -f  "Section7YChallange.mk"
clean:
	@echo "----------Cleaning project:[ Section7YChallange - Debug ]----------"
	@cd "Section7YChallange" && "$(MAKE)" -f  "Section7YChallange.mk" clean
