.PHONY: clean All

All:
	@echo "----------Building project:[ 02Dereferencing - Debug ]----------"
	@cd "02Dereferencing" && "$(MAKE)" -f  "02Dereferencing.mk"
clean:
	@echo "----------Cleaning project:[ 02Dereferencing - Debug ]----------"
	@cd "02Dereferencing" && "$(MAKE)" -f  "02Dereferencing.mk" clean
