.PHONY: clean All

All:
	@echo "----------Building project:[ Homework01.12.21 - Debug ]----------"
	@cd "Homework01.12.21" && "$(MAKE)" -f  "Homework01.12.21.mk"
clean:
	@echo "----------Cleaning project:[ Homework01.12.21 - Debug ]----------"
	@cd "Homework01.12.21" && "$(MAKE)" -f  "Homework01.12.21.mk" clean
