.PHONY: clean All

All:
	@echo "----------Building project:[ FinalX2 - Debug ]----------"
	@cd "FinalX2" && "$(MAKE)" -f  "FinalX2.mk"
clean:
	@echo "----------Cleaning project:[ FinalX2 - Debug ]----------"
	@cd "FinalX2" && "$(MAKE)" -f  "FinalX2.mk" clean
