.PHONY: clean All

All:
	@echo "----------Building project:[ Challange - Debug ]----------"
	@cd "Challange" && "$(MAKE)" -f  "Challange.mk"
clean:
	@echo "----------Cleaning project:[ Challange - Debug ]----------"
	@cd "Challange" && "$(MAKE)" -f  "Challange.mk" clean
