.PHONY: clean All

All:
	@echo "----------Building project:[ Section8YChallange - Debug ]----------"
	@cd "Section8YChallange" && "$(MAKE)" -f  "Section8YChallange.mk"
clean:
	@echo "----------Cleaning project:[ Section8YChallange - Debug ]----------"
	@cd "Section8YChallange" && "$(MAKE)" -f  "Section8YChallange.mk" clean
