.PHONY: clean All

All:
	@echo "----------Building project:[ Expressions - Debug ]----------"
	@cd "Expressions" && "$(MAKE)" -f  "Expressions.mk"
clean:
	@echo "----------Cleaning project:[ Expressions - Debug ]----------"
	@cd "Expressions" && "$(MAKE)" -f  "Expressions.mk" clean
