.PHONY: clean All

All:
	@echo "----------Building project:[ OOP11May2021 - Debug ]----------"
	@cd "OOP11May2021" && "$(MAKE)" -f  "OOP11May2021.mk"
clean:
	@echo "----------Cleaning project:[ OOP11May2021 - Debug ]----------"
	@cd "OOP11May2021" && "$(MAKE)" -f  "OOP11May2021.mk" clean
