.PHONY: clean All

All:
	@echo "----------Building project:[ OOPHomework1 - Debug ]----------"
	@cd "OOPHomework1" && "$(MAKE)" -f  "OOPHomework1.mk"
clean:
	@echo "----------Cleaning project:[ OOPHomework1 - Debug ]----------"
	@cd "OOPHomework1" && "$(MAKE)" -f  "OOPHomework1.mk" clean
