.PHONY: clean All

All:
	@echo "----------Building project:[ OOP20May2021 - Debug ]----------"
	@cd "OOP20May2021" && "$(MAKE)" -f  "OOP20May2021.mk"
clean:
	@echo "----------Cleaning project:[ OOP20May2021 - Debug ]----------"
	@cd "OOP20May2021" && "$(MAKE)" -f  "OOP20May2021.mk" clean
