.PHONY: clean All

All:
	@echo "----------Building project:[ Homework - Debug ]----------"
	@cd "Homework" && "$(MAKE)" -f  "Homework.mk"
clean:
	@echo "----------Cleaning project:[ Homework - Debug ]----------"
	@cd "Homework" && "$(MAKE)" -f  "Homework.mk" clean
