.PHONY: clean All

All:
	@echo "----------Building project:[ SectionChallange - Debug ]----------"
	@cd "SectionChallange" && "$(MAKE)" -f  "SectionChallange.mk"
clean:
	@echo "----------Cleaning project:[ SectionChallange - Debug ]----------"
	@cd "SectionChallange" && "$(MAKE)" -f  "SectionChallange.mk" clean
