.PHONY: clean All

All:
	@echo "----------Building project:[ 07FunctionOverloading - Debug ]----------"
	@cd "07FunctionOverloading" && "$(MAKE)" -f  "07FunctionOverloading.mk"
clean:
	@echo "----------Cleaning project:[ 07FunctionOverloading - Debug ]----------"
	@cd "07FunctionOverloading" && "$(MAKE)" -f  "07FunctionOverloading.mk" clean
