.PHONY: clean All

All:
	@echo "----------Building project:[ 05FunctionParameters - Debug ]----------"
	@cd "05FunctionParameters" && "$(MAKE)" -f  "05FunctionParameters.mk"
clean:
	@echo "----------Cleaning project:[ 05FunctionParameters - Debug ]----------"
	@cd "05FunctionParameters" && "$(MAKE)" -f  "05FunctionParameters.mk" clean
