.PHONY: clean All

All:
	@echo "----------Building project:[ 11RecursiveFunctions - Debug ]----------"
	@cd "11RecursiveFunctions" && "$(MAKE)" -f  "11RecursiveFunctions.mk"
clean:
	@echo "----------Cleaning project:[ 11RecursiveFunctions - Debug ]----------"
	@cd "11RecursiveFunctions" && "$(MAKE)" -f  "11RecursiveFunctions.mk" clean
