.PHONY: clean All

All:
	@echo "----------Building project:[ Homework.for.holidays - Debug ]----------"
	@cd "Homework.for.holidays" && "$(MAKE)" -f  "Homework.for.holidays.mk"
clean:
	@echo "----------Cleaning project:[ Homework.for.holidays - Debug ]----------"
	@cd "Homework.for.holidays" && "$(MAKE)" -f  "Homework.for.holidays.mk" clean
