.PHONY: clean All

All:
	@echo "----------Building project:[ assignment1 - Debug ]----------"
	@cd "assignment1" && "$(MAKE)" -f  "assignment1.mk"
clean:
	@echo "----------Cleaning project:[ assignment1 - Debug ]----------"
	@cd "assignment1" && "$(MAKE)" -f  "assignment1.mk" clean
