.PHONY: clean All

All:
	@echo "----------Building project:[ ITStep26Jan2021 - Debug ]----------"
	@cd "ITStep26Jan2021" && "$(MAKE)" -f  "ITStep26Jan2021.mk"
clean:
	@echo "----------Cleaning project:[ ITStep26Jan2021 - Debug ]----------"
	@cd "ITStep26Jan2021" && "$(MAKE)" -f  "ITStep26Jan2021.mk" clean
