.PHONY: clean All

All:
	@echo "----------Building project:[ ItStep09Feb2021Homework2 - Debug ]----------"
	@cd "ItStep09Feb2021Homework2" && "$(MAKE)" -f  "ItStep09Feb2021Homework2.mk"
clean:
	@echo "----------Cleaning project:[ ItStep09Feb2021Homework2 - Debug ]----------"
	@cd "ItStep09Feb2021Homework2" && "$(MAKE)" -f  "ItStep09Feb2021Homework2.mk" clean
