.PHONY: clean All

All:
	@echo "----------Building project:[ Homework-08-12-2020-V2 - Debug ]----------"
	@cd "Homework-08-12-2020-V2" && "$(MAKE)" -f  "Homework-08-12-2020-V2.mk"
clean:
	@echo "----------Cleaning project:[ Homework-08-12-2020-V2 - Debug ]----------"
	@cd "Homework-08-12-2020-V2" && "$(MAKE)" -f  "Homework-08-12-2020-V2.mk" clean
